packages:
  - web
  - docs

catalog:
  '@fontsource-variable/geist': ^5.2.9
  '@fontsource-variable/geist-mono': ^5.2.8
  '@types/node': ^25.9.3
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  react: 19.2.7
  react-dom: 19.2.7
  typescript: ~6.0.3

onlyBuiltDependencies:
  - '@goreleaser/goreleaser'
  - '@parcel/watcher'
  - msw

overrides:
  react: 19.2.7
  react-dom: 19.2.7
